name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        run: |
          python3.11 -m ensurepip
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -r MyFunction/requirements.txt
      

      - name: Set environment variables
        run: |
          echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> $GITHUB_ENV
          echo "COSMOS_KEY=${{ secrets.COSMOS_KEY }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd az_function
          python3.11 -m pytest --verbose

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        run: |
          az deployment group create \
          --resource-group RsrceIbtahaj \
          --template-file templates/merged-template.json \
          --parameters templates/merged-parameters.json
