name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'  # Use specific available version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MyFunction/requirements.txt

    - name: Set environment variables
      run: |
        echo "COSMOS_DB_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> $GITHUB_ENV
        echo "COSMOS_DB_KEY=${{ secrets.COSMOS_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd az_function
        pytest

    - name: Azure Login
      uses: azure/login@v1

      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group RsrceIbtahaj --template-file templates/merged-template.json --parameters templates/merged-parameters.json
